### ISSUE TITLE
Userdefined rootdevicehint support 

### ISSUE THREAD

**Issue by mikkosest** [metal3-io/baremetal-operator#435] opened 2020-02-19 15:03 UTC
Hi, we would need a way to propagate rootdevicehint information from BMO user to the BMH object in CR. This would require update in BMO CR, CRD, controller and BMO ironic pkg. 
How does that sound @zaneb and @dhellmann ?

**Comment by dhellmann** [comment] 2020-02-19 18:57
We have minimal support for root device hints through the hardware profile, but I think we want to deprecate that in favor of a new field just for the root device hint.  I know @yrobla has been looking into this already. Let's get a design document posted for review in the metal3-docs repo.

**Comment by stbenjam** [comment] 2020-02-19 19:31
Indeed, this is a dupe of https://github.com/metal3-io/baremetal-operator/issues/400

/close

**Closed by stbenjam** 2020-02-19 19:31 UTC
