### ISSUE TITLE
 baremetal IPI power_interface for irmc miss IPMI credentials

### ISSUE THREAD

**Issue by zhouhao3** [metal3-io/baremetal-operator#879] opened 2021-05-14 07:48 UTC
When we deployed bare metal using IPI, we encountered the following errors:
```
| last_error             | Failed to validate power driver interface for node e88070b5-afe2-4132-b697-93ee2bf10c1b. Error: Missing the following IPMI credentials in node's driver_info: ['ipmi_address']
```
Check that there is no ipmi related information in driver_info
```
| driver_info            | {​​​​​​​'deploy_kernel': 'http://192.168.20.2:80/images/ironic-python-agent.kernel', 'deploy_ramdisk': 'http://192.168.20.2:80/images/ironic-python-agent.initramfs', 'irmc_address': '192.168.30.25', 'irmc_password': '******', 'irmc_username': 'admin'}​​​​​​​ |
```
But in our previous use, there will be ipmi information in driver_info.

I think it may be related to this PR. https://github.com/metal3-io/baremetal-operator/pull/848

**Comment by zhouhao3** [comment] 2021-05-14 09:30
The reason for this error should be as @dtantsur  [commented](https://github.com/metal3-io/baremetal-operator/pull/848#discussion_r607720722). I modified the `power_interface` directly through baremetal, so I did not know bug. Sorry for this problem.

**Comment by hardys** [comment] 2021-05-14 12:55
@zhouhao3 can you confirm if the error is when deploying the master/controlplane nodes, or the worker hosts?

The discussion in #848 seems to indicate the ipmi credentials are provided via the ironic driver ref https://opendev.org/openstack/ironic/src/branch/master/ironic/drivers/modules/irmc/common.py#L160-L174

**Comment by hs0210** [comment] 2021-05-15 04:38
[#4908](https://github.com/openshift/installer/pull/4908) seems to be the cause of the error, as the error occurred just after it was merged.

**Comment by zhouhao3** [comment] 2021-05-17 02:26
@hardys It can be confirmed that this error occurred when the master was deployed. As there is no ipmi-related information in the driver_info, an error occurred.  When I created this PR, I used baremetal's command to directly modify the value of power_interface, so there was no error at that time. I am solving the problem, and currently think that some processing should be added to ironic so that there is ipmi_tool related content in the baremetal deviceinfo field.
@dtantsur Can you take a look please?

**Comment by zhouhao3** [comment] 2021-05-17 03:57
We sent a PR https://github.com/metal3-io/baremetal-operator/pull/880 to fix this problem.

**Closed** 2021-05-19 11:02 UTC
