### ISSUE TITLE
Redfish connection fails due to failing to verify the certificate

### ISSUE THREAD

**Issue by rlopez133** [metal3-io/baremetal-operator#415] opened 2020-02-04 18:05 UTC
When attempting to use to redfish instead of ipmi, the ironic-conductor container reports the following error on the bootstrap VM

`2020-02-04 17:23:43.595 1 ERROR ironic.drivers.modules.redfish.utils [req-12be7bb9-1a2c-4572-b139-31ec4ddc90d4 - - - - -] Failed to connect to Redfish at https://<IP> for node 8161c778-967d-4bf5-b9c4-8e66b27698e0. Error: Redfish connection failed for node 8161c778-967d-4bf5-b9c4-8e66b27698e0: Unable to connect to https://<IP>/redfish/v1/. Error: HTTPSConnectionPool(host='<IP>', port=443): Max retries exceeded with url: /redfish/v1/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),)): ironic.common.exception.RedfishConnectionError: Redfish connection failed for node 8161c778-967d-4bf5-b9c4-8e66b27698e0: Unable to connect to https://<IP>/redfish/v1/. Error: HTTPSConnectionPool(host='<IP>', port=443): Max retries exceeded with url: /redfish/v1/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),))
2020-02-04 17:23:43.596 1 ERROR ironic.conductor.manager [req-12be7bb9-1a2c-4572-b139-31ec4ddc90d4 - - - - -] Failed to get power state for node 8161c778-967d-4bf5-b9c4-8e66b27698e0. Error: Redfish connection failed for node 8161c778-967d-4bf5-b9c4-8e66b27698e0: Unable to connect to https://<IP>/redfish/v1/. Error: HTTPSConnectionPool(host='<IP>', port=443): Max retries exceeded with url: /redfish/v1/ (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:897)'),)
)`

Based on discussions in slack, it seems that the fix would be to add "redfish_verify_ca": False since the CA is self signed. The location would be: https://github.com/metal3-io/baremetal-operator/blob/master/pkg/bmc/redfish.go#L89

**Comment by stbenjam** [comment] 2020-02-04 18:07
Will be fixed by https://github.com/metal3-io/baremetal-operator/pull/396

**Comment by stbenjam** [comment] 2020-02-04 18:07
Dupe of https://github.com/metal3-io/baremetal-operator/issues/392

**Closed by stbenjam** 2020-02-04 18:07 UTC
